server:
  port: 8091

spring:
  application:
    name: crm-service
  codec:
    max-in-memory-size: 4194304
  cloud:
    openfeign:
      client:
        config:
          default:
            connectTimeout: 5000
            readTimeout: 300000
            loggerLevel: basic
  kafka:
    consumer:
      group-id: crm-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"

logging:
  level:
    com:
      dpvn:
        crm:
          client: DEBUG

---
spring:
  config:
    activate:
      on-profile: default, command, local
  data:
    redis:
      host: localhost
      port: 6379
  kafka:
    bootstrap-servers: localhost:9092

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true

---
spring:
  config:
    activate:
      on-profile: production
  data:
    redis:
      host: dpvn-server-redis
      port: 6379
  kafka:
    bootstrap-servers: dpvn-kafka:9092

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://dpvn-eureka-server:8761/eureka
  instance:
    prefer-ip-address: true
